// <auto-generated />
using System;
using CattleManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CattleManager.Data.Migrations;

[DbContext(typeof(CattleDbContext))]
partial class CattleDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

        modelBuilder.Entity("CattleManager.Data.Entities.Animal", b =>
        {
            b.Property<int>("AnimalId").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<int>("HerdId").HasColumnType("INTEGER");
            b.Property<string>("BarnName").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("RegisteredName").HasMaxLength(200).HasColumnType("TEXT");
            b.Property<string>("RegistrationNumber").HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("RegistrationOrganization").HasMaxLength(200).HasColumnType("TEXT");
            b.Property<int>("BreedId").HasColumnType("INTEGER");
            b.Property<int>("Gender").HasColumnType("INTEGER");
            b.Property<int>("Status").HasColumnType("INTEGER");
            b.Property<decimal?>("Height").HasPrecision(10, 2).HasColumnType("TEXT");
            b.Property<int>("HeightUnit").HasColumnType("INTEGER");
            b.Property<decimal?>("Weight").HasPrecision(10, 2).HasColumnType("TEXT");
            b.Property<int>("WeightUnit").HasColumnType("INTEGER");
            b.Property<string>("Coloring").HasMaxLength(500).HasColumnType("TEXT");
            b.Property<string>("PhotoPath").HasMaxLength(1000).HasColumnType("TEXT");
            b.Property<DateTime>("BirthDate").HasColumnType("TEXT");
            b.Property<DateTime?>("DateAcquired").HasColumnType("TEXT");
            b.Property<string>("CurrentLocation").HasMaxLength(200).HasColumnType("TEXT");
            b.Property<string>("BreedersName").HasMaxLength(200).HasColumnType("TEXT");
            b.Property<string>("CurrentOwner").HasMaxLength(200).HasColumnType("TEXT");
            b.Property<int?>("SireId").HasColumnType("INTEGER");
            b.Property<int?>("DamId").HasColumnType("INTEGER");
            b.Property<string>("ExternalSireName").HasMaxLength(200).HasColumnType("TEXT");
            b.Property<string>("ExternalDamName").HasMaxLength(200).HasColumnType("TEXT");
            b.Property<DateTime?>("LastWormingDate").HasColumnType("TEXT");
            b.Property<DateTime?>("LastVaccinationDate").HasColumnType("TEXT");
            b.Property<DateTime?>("LastHealthCheckDate").HasColumnType("TEXT");
            b.Property<string>("HealthNotes").HasColumnType("TEXT");
            b.Property<bool>("IsBreeding").HasColumnType("INTEGER");
            b.Property<bool>("IsPregnant").HasColumnType("INTEGER");
            b.Property<int?>("PregnancySireId").HasColumnType("INTEGER");
            b.Property<DateTime?>("ExpectedDueDate").HasColumnType("TEXT");
            b.Property<DateTime?>("BreedingDate").HasColumnType("TEXT");
            b.Property<string>("ReproductionNotes").HasColumnType("TEXT");
            b.Property<int?>("MaleBreedingStatus").HasColumnType("INTEGER");
            b.Property<bool>("IsSampleData").HasDefaultValue(false).HasColumnType("INTEGER");
            b.Property<DateTime>("CreatedDate").HasColumnType("TEXT");
            b.Property<DateTime>("ModifiedDate").HasColumnType("TEXT");
            b.HasKey("AnimalId");
            b.HasIndex("HerdId", "BarnName").IsUnique();
            b.ToTable("Animals");
        });

        modelBuilder.Entity("CattleManager.Data.Entities.Herd", b =>
        {
            b.Property<int>("HerdId").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<int>("FarmId").HasColumnType("INTEGER");
            b.Property<string>("HerdName").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
            b.Property<string>("HerdType").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
            b.Property<bool>("IsActive").HasDefaultValue(true).HasColumnType("INTEGER");
            b.Property<bool>("IsSampleData").HasDefaultValue(false).HasColumnType("INTEGER");
            b.Property<DateTime>("CreatedDate").HasColumnType("TEXT");
            b.HasKey("HerdId");
            b.ToTable("Herds");
        });

        modelBuilder.Entity("CattleManager.Data.Entities.Farm", b =>
        {
            b.Property<int>("FarmId").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<string>("FarmName").IsRequired().HasMaxLength(200).HasColumnType("TEXT");
            b.Property<string>("Address").HasMaxLength(500).HasColumnType("TEXT");
            b.Property<string>("ContactInfo").HasMaxLength(500).HasColumnType("TEXT");
            b.HasKey("FarmId");
            b.ToTable("Farms");
        });

        modelBuilder.Entity("CattleManager.Data.Entities.Breed", b =>
        {
            b.Property<int>("BreedId").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<string>("BreedName").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
            b.Property<bool>("IsStandardBreed").HasColumnType("INTEGER");
            b.HasKey("BreedId");
            b.ToTable("Breeds");
            b.HasData(
                new { BreedId = 1, BreedName = "Angus", IsStandardBreed = true },
                new { BreedId = 2, BreedName = "Hereford", IsStandardBreed = true },
                new { BreedId = 3, BreedName = "Brahman", IsStandardBreed = true },
                new { BreedId = 4, BreedName = "Charolais", IsStandardBreed = true },
                new { BreedId = 5, BreedName = "Simmental", IsStandardBreed = true },
                new { BreedId = 6, BreedName = "Zebu", IsStandardBreed = true },
                new { BreedId = 7, BreedName = "Miniature Zebu", IsStandardBreed = true },
                new { BreedId = 8, BreedName = "Longhorn", IsStandardBreed = true },
                new { BreedId = 9, BreedName = "Shorthorn", IsStandardBreed = true },
                new { BreedId = 10, BreedName = "Limousin", IsStandardBreed = true },
                new { BreedId = 11, BreedName = "Gelbvieh", IsStandardBreed = true },
                new { BreedId = 12, BreedName = "Brangus", IsStandardBreed = true },
                new { BreedId = 13, BreedName = "Beefmaster", IsStandardBreed = true },
                new { BreedId = 14, BreedName = "Mixed Breed", IsStandardBreed = true }
            );
        });

        modelBuilder.Entity("CattleManager.Data.Entities.HealthRecord", b =>
        {
            b.Property<int>("HealthRecordId").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<int>("AnimalId").HasColumnType("INTEGER");
            b.Property<DateTime>("RecordDate").HasColumnType("TEXT");
            b.Property<int>("RecordType").HasColumnType("INTEGER");
            b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("TEXT");
            b.Property<string>("TreatmentDetails").HasColumnType("TEXT");
            b.Property<string>("VeterinarianName").HasMaxLength(200).HasColumnType("TEXT");
            b.Property<bool>("IsSampleData").HasDefaultValue(false).HasColumnType("INTEGER");
            b.HasKey("HealthRecordId");
            b.ToTable("HealthRecords");
        });

        modelBuilder.Entity("CattleManager.Data.Entities.BreedingRecord", b =>
        {
            b.Property<int>("BreedingRecordId").ValueGeneratedOnAdd().HasColumnType("INTEGER");
            b.Property<int>("SireId").HasColumnType("INTEGER");
            b.Property<int>("DamId").HasColumnType("INTEGER");
            b.Property<DateTime>("BreedingDate").HasColumnType("TEXT");
            b.Property<DateTime>("ExpectedDueDate").HasColumnType("TEXT");
            b.Property<DateTime?>("CalvingDate").HasColumnType("TEXT");
            b.Property<int?>("OffspringId").HasColumnType("INTEGER");
            b.Property<string>("OutcomeNotes").HasColumnType("TEXT");
            b.Property<bool>("IsSampleData").HasDefaultValue(false).HasColumnType("INTEGER");
            b.HasKey("BreedingRecordId");
            b.ToTable("BreedingRecords");
        });

        modelBuilder.Entity("CattleManager.Data.Entities.AppSetting", b =>
        {
            b.Property<string>("Key").IsRequired().HasMaxLength(100).HasColumnType("TEXT");
            b.Property<string>("Value").IsRequired().HasDefaultValue("").HasColumnType("TEXT");
            b.HasKey("Key");
            b.ToTable("AppSettings");
        });
#pragma warning restore 612, 618
    }
}
