using CattleManager.Core.Models;
using CsvHelper;
using CsvHelper.Configuration;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.IO;

namespace CattleManager.Core.Services;

[ExcludeFromCodeCoverage(Justification = "PDF/CSV generation requires real filesystem and rendering engine")]
public class ExportService
{
    static ExportService()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public void ExportHerdToCsv(IReadOnlyList<AnimalDto> animals, string filePath)
    {
        var config = new CsvConfiguration(CultureInfo.InvariantCulture)
        {
            HasHeaderRecord = true
        };
        using var writer = new StreamWriter(filePath);
        using var csv = new CsvWriter(writer, config);

        csv.WriteHeader<CsvAnimalRow>();
        csv.NextRecord();
        foreach (var a in animals)
        {
            csv.WriteRecord(new CsvAnimalRow(a));
            csv.NextRecord();
        }
    }

    public void ExportAnimalProfileToPdf(AnimalDto animal, string filePath)
    {
        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header().Text($"Cattle Manager — Animal Profile")
                    .SemiBold().FontSize(18).FontColor(Colors.Green.Darken3);

                page.Content().Column(col =>
                {
                    col.Spacing(10);

                    col.Item().Text($"{animal.BarnName}").Bold().FontSize(20);
                    if (!string.IsNullOrEmpty(animal.RegisteredName))
                        col.Item().Text($"Registered: {animal.RegisteredName}").Italic();

                    col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                    col.Item().Row(row =>
                    {
                        row.RelativeItem().Column(c =>
                        {
                            c.Item().Text("Basic Information").Bold().FontSize(13);
                            c.Item().Text($"Breed: {animal.BreedName}");
                            c.Item().Text($"Gender: {animal.Gender}");
                            c.Item().Text($"Status: {animal.Status}");
                            c.Item().Text($"Birth Date: {animal.BirthDate:MMMM d, yyyy}");
                            c.Item().Text($"Age: {animal.AgeDisplay}");
                        });
                        row.RelativeItem().Column(c =>
                        {
                            c.Item().Text("Physical").Bold().FontSize(13);
                            c.Item().Text($"Weight: {animal.WeightDisplay}");
                            c.Item().Text($"Height: {animal.HeightDisplay}");
                            c.Item().Text($"Coloring: {animal.Coloring}");
                        });
                    });

                    col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                    col.Item().Row(row =>
                    {
                        row.RelativeItem().Column(c =>
                        {
                            c.Item().Text("Health & Husbandry").Bold().FontSize(13);
                            c.Item().Text($"Last Worming: {animal.LastWormingDate?.ToString("MM/dd/yyyy") ?? "Not recorded"}");
                            c.Item().Text($"Last Vaccination: {animal.LastVaccinationDate?.ToString("MM/dd/yyyy") ?? "Not recorded"}");
                            c.Item().Text($"Last Health Check: {animal.LastHealthCheckDate?.ToString("MM/dd/yyyy") ?? "Not recorded"}");
                        });
                        row.RelativeItem().Column(c =>
                        {
                            c.Item().Text("Lineage").Bold().FontSize(13);
                            c.Item().Text($"Sire: {animal.SireBarnName ?? animal.ExternalSireName ?? "Unknown"}");
                            c.Item().Text($"Dam: {animal.DamBarnName ?? animal.ExternalDamName ?? "Unknown"}");
                        });
                    });

                    if (!string.IsNullOrEmpty(animal.HealthNotes))
                    {
                        col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                        col.Item().Text("Health Notes").Bold();
                        col.Item().Text(animal.HealthNotes);
                    }
                });

                page.Footer().AlignCenter()
                    .Text(x =>
                    {
                        x.Span("Generated by Cattle Manager — ");
                        x.Span(DateTime.Now.ToString("MM/dd/yyyy HH:mm"));
                    });
            });
        }).GeneratePdf(filePath);
    }

    private record CsvAnimalRow(AnimalDto A)
    {
        public string BarnName => A.BarnName;
        public string? RegisteredName => A.RegisteredName;
        public string Breed => A.BreedName;
        public string Gender => A.Gender.ToString();
        public string Status => A.Status.ToString();
        public string BirthDate => A.BirthDate.ToString("MM/dd/yyyy");
        public string Age => A.AgeDisplay;
        public string Weight => A.WeightDisplay;
        public string Height => A.HeightDisplay;
        public string? Coloring => A.Coloring;
        public string? Location => A.CurrentLocation;
        public string? LastWorming => A.LastWormingDate?.ToString("MM/dd/yyyy");
        public string? LastVaccination => A.LastVaccinationDate?.ToString("MM/dd/yyyy");
        public string? Sire => A.SireBarnName ?? A.ExternalSireName;
        public string? Dam => A.DamBarnName ?? A.ExternalDamName;
    }
}
