using CattleManager.Core.Models;
using CsvHelper;
using CsvHelper.Configuration;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.IO;

namespace CattleManager.Core.Services;

[ExcludeFromCodeCoverage(Justification = "PDF/CSV generation requires real filesystem and rendering engine")]
public class ExportService
{
    static ExportService()
    {
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public void ExportHerdToCsv(IReadOnlyList<AnimalDto> animals, string filePath)
    {
        var config = new CsvConfiguration(CultureInfo.InvariantCulture)
        {
            HasHeaderRecord = true
        };
        using var writer = new StreamWriter(filePath);
        using var csv = new CsvWriter(writer, config);

        csv.WriteHeader<CsvAnimalRow>();
        csv.NextRecord();
        foreach (var a in animals)
        {
            csv.WriteRecord(new CsvAnimalRow(a));
            csv.NextRecord();
        }
    }

    public void ExportAnimalProfileToPdf(AnimalDto animal, string filePath)
    {
        Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header().Text($"Herd Master — Animal Profile")
                    .SemiBold().FontSize(18).FontColor(Colors.Green.Darken3);

                page.Content().Column(col =>
                {
                    col.Spacing(10);

                    col.Item().Text($"{animal.BarnName}").Bold().FontSize(20);
                    if (!string.IsNullOrEmpty(animal.RegisteredName))
                        col.Item().Text($"Registered: {animal.RegisteredName}").Italic();

                    col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                    col.Item().Row(row =>
                    {
                        row.RelativeItem().Column(c =>
                        {
                            c.Item().Text("Basic Information").Bold().FontSize(13);
                            c.Item().Text($"Breed: {animal.BreedName}");
                            c.Item().Text($"Gender: {animal.Gender}");
                            c.Item().Text($"Status: {animal.Status}");
                            c.Item().Text($"Birth Date: {animal.BirthDate:MMMM d, yyyy}");
                            c.Item().Text($"Age: {animal.AgeDisplay}");
                        });
                        row.RelativeItem().Column(c =>
                        {
                            c.Item().Text("Physical").Bold().FontSize(13);
                            c.Item().Text($"Weight: {animal.WeightDisplay}");
                            c.Item().Text($"Height: {animal.HeightDisplay}");
                            c.Item().Text($"Coloring: {animal.Coloring}");
                        });
                    });

                    col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                    col.Item().Row(row =>
                    {
                        row.RelativeItem().Column(c =>
                        {
                            c.Item().Text("Health & Husbandry").Bold().FontSize(13);
                            c.Item().Text($"Last Worming: {animal.LastWormingDate?.ToString("MM/dd/yyyy") ?? "Not recorded"}");
                            c.Item().Text($"Last Vaccination: {animal.LastVaccinationDate?.ToString("MM/dd/yyyy") ?? "Not recorded"}");
                            c.Item().Text($"Last Health Check: {animal.LastHealthCheckDate?.ToString("MM/dd/yyyy") ?? "Not recorded"}");
                        });
                        row.RelativeItem().Column(c =>
                        {
                            c.Item().Text("Lineage").Bold().FontSize(13);
                            c.Item().Text($"Sire: {animal.SireBarnName ?? animal.ExternalSireName ?? "Unknown"}");
                            c.Item().Text($"Dam: {animal.DamBarnName ?? animal.ExternalDamName ?? "Unknown"}");
                        });
                    });

                    if (!string.IsNullOrEmpty(animal.HealthNotes))
                    {
                        col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                        col.Item().Text("Health Notes").Bold();
                        col.Item().Text(animal.HealthNotes);
                    }
                });

                page.Footer().AlignCenter()
                    .Text(x =>
                    {
                        x.Span("Generated by Herd Master — ");
                        x.Span(DateTime.Now.ToString("MM/dd/yyyy HH:mm"));
                    });
            });
        }).GeneratePdf(filePath);
    }

    // ---- Financial report PDFs ----

    public void ExportProfitAndLossToPdf(ProfitAndLossDto pl, DateTime from, DateTime to, string path)
    {
        Document.Create(c => c.Page(page =>
        {
            page.Size(PageSizes.A4);
            page.Margin(2, Unit.Centimetre);
            page.DefaultTextStyle(x => x.FontSize(10));
            page.Header().Text("Herd Master — Profit & Loss Statement")
                .SemiBold().FontSize(16).FontColor(Colors.Green.Darken3);
            page.Content().Column(col =>
            {
                col.Spacing(5);
                col.Item().Text($"Period: {from:MMMM d, yyyy}  —  {to:MMMM d, yyyy}").Italic();
                col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                col.Item().PaddingTop(4).Text("INCOME").Bold().FontSize(12);
                foreach (var item in pl.IncomeByCategory)
                    AddLineRow(col, item.Category, item.Amount, false);
                AddLineRow(col, "Gross Revenue", pl.GrossRevenue, true);

                col.Item().PaddingTop(6).Text("EXPENSES").Bold().FontSize(12);
                foreach (var item in pl.ExpensesByCategory)
                    AddLineRow(col, item.Category, item.Amount, false);
                AddLineRow(col, "Total Cash Expenses", pl.TotalExpenses, true);
                AddLineRow(col, "  Interest Expense", pl.InterestExpense, false, italic: true);
                AddLineRow(col, "  Depreciation", pl.DepreciationTotal, false, italic: true);

                col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                col.Item().Row(row =>
                {
                    row.RelativeItem().Text("NET FARM INCOME").Bold().FontSize(12);
                    row.ConstantItem(110)
                       .Text(pl.NetFarmIncome.ToString("C")).Bold().FontSize(12).AlignRight();
                });
            });
            page.Footer().AlignCenter().Text(x =>
            {
                x.Span("Generated by Herd Master — ");
                x.Span(DateTime.Now.ToString("MM/dd/yyyy HH:mm"));
            });
        })).GeneratePdf(path);
    }

    public void ExportBalanceSheetToPdf(BalanceSheetDto bs, string path)
    {
        Document.Create(c => c.Page(page =>
        {
            page.Size(PageSizes.A4);
            page.Margin(2, Unit.Centimetre);
            page.DefaultTextStyle(x => x.FontSize(10));
            page.Header().Text("Herd Master — Balance Sheet")
                .SemiBold().FontSize(16).FontColor(Colors.Green.Darken3);
            page.Content().Column(col =>
            {
                col.Spacing(4);
                col.Item().Text($"As of {bs.AsOf:MMMM d, yyyy}").Italic();
                col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                col.Item().PaddingTop(4).Text("ASSETS").Bold().FontSize(12);
                col.Item().Text("Current Assets").Bold();
                AddLineRow(col, "  Cash (approximate)", bs.CashApproximate, false);
                AddLineRow(col, "  Livestock Inventory", bs.LivestockInventoryValue, false);
                AddLineRow(col, "Total Current Assets", bs.TotalCurrentAssets, true);

                col.Item().PaddingTop(4).Text("Fixed Assets").Bold();
                foreach (var a in bs.FixedAssets)
                    AddLineRow(col, $"  {a.Name}", a.BookValue, false);
                AddLineRow(col, "  Gross Fixed Assets", bs.TotalFixedAssetsGross, false, italic: true);
                AddLineRow(col, "  Accumulated Depreciation", -bs.AccumulatedDepreciation, false, italic: true);
                AddLineRow(col, "Total Fixed Assets (net)", bs.TotalFixedAssetsNet, true);

                col.Item().LineHorizontal(0.5f).LineColor(Colors.Grey.Lighten2);
                AddLineRow(col, "TOTAL ASSETS", bs.TotalAssets, true, fontSize: 11);

                col.Item().PaddingTop(6).Text("LIABILITIES").Bold().FontSize(12);
                col.Item().Text("Current Liabilities").Bold();
                AddLineRow(col, "  Operating Line of Credit", bs.OperatingLineBalance, false);
                AddLineRow(col, "Total Current Liabilities", bs.TotalCurrentLiabilities, true);

                col.Item().PaddingTop(4).Text("Long-Term Liabilities").Bold();
                foreach (var loan in bs.LongTermLoans)
                    AddLineRow(col, $"  {loan.LenderName} ({loan.LoanType})", loan.Balance, false);
                AddLineRow(col, "Total Long-Term Liabilities", bs.TotalLongTermLiabilities, true);

                col.Item().LineHorizontal(0.5f).LineColor(Colors.Grey.Lighten2);
                AddLineRow(col, "TOTAL LIABILITIES", bs.TotalLiabilities, true, fontSize: 11);

                col.Item().PaddingTop(4).LineHorizontal(1).LineColor(Colors.Grey.Lighten1);
                AddLineRow(col, "OWNER'S EQUITY", bs.OwnersEquity, true, fontSize: 12);
            });
            page.Footer().AlignCenter().Text(x =>
            {
                x.Span("Generated by Herd Master — ");
                x.Span(DateTime.Now.ToString("MM/dd/yyyy HH:mm"));
            });
        })).GeneratePdf(path);
    }

    public void ExportTaxSummaryToPdf(TaxSummaryDto tax, string path)
    {
        Document.Create(c => c.Page(page =>
        {
            page.Size(PageSizes.A4);
            page.Margin(2, Unit.Centimetre);
            page.DefaultTextStyle(x => x.FontSize(10));
            page.Header().Text($"Herd Master — Tax Summary {tax.FiscalYear}")
                .SemiBold().FontSize(16).FontColor(Colors.Green.Darken3);
            page.Content().Column(col =>
            {
                col.Spacing(5);
                col.Item().Text($"Fiscal Year {tax.FiscalYear}").Italic();
                col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                col.Item().PaddingTop(4).Text("INCOME SUMMARY").Bold().FontSize(12);
                AddLineRow(col, "Gross Livestock Sales", tax.TotalGrossSales, false);
                AddLineRow(col, "Other Farm Income", tax.TotalOtherIncome, false);
                AddLineRow(col, "Total Expenses", tax.TotalExpenses, false);
                AddLineRow(col, "Net Farm Income", tax.NetFarmIncome, true);

                col.Item().PaddingTop(6).Text("ESTIMATED TAX LIABILITY").Bold().FontSize(12);
                AddLineRow(col, "Self-Employment Tax (15.3%)", tax.SelfEmploymentTax, false);
                AddLineRow(col, "Estimated Federal Income Tax", tax.EstimatedFederalTax, false);
                AddLineRow(col, "Estimated State Income Tax", tax.EstimatedStateTax, false);
                AddLineRow(col, "Total Estimated Taxes",
                    tax.SelfEmploymentTax + tax.EstimatedFederalTax + tax.EstimatedStateTax, true);

                if (tax.ScheduleFItems.Count > 0)
                {
                    col.Item().PaddingTop(6).Text("SCHEDULE F MAPPING").Bold().FontSize(12);
                    foreach (var item in tax.ScheduleFItems)
                        col.Item().Row(row =>
                        {
                            row.RelativeItem().Text(item.LineDescription).FontSize(9);
                            row.ConstantItem(90).Text(item.Amount.ToString("C")).AlignRight().FontSize(9);
                        });
                }

                if (tax.CapitalGainEvents.Count > 0)
                {
                    col.Item().PaddingTop(6).Text("CAPITAL GAIN / LOSS EVENTS").Bold().FontSize(12);
                    foreach (var evt in tax.CapitalGainEvents)
                    {
                        col.Item().Text($"  {evt.AssetDescription} — " +
                            $"Acquired {evt.AcquisitionDate:MM/dd/yyyy}, " +
                            $"Sold {evt.SaleDate:MM/dd/yyyy} " +
                            $"({(evt.IsLongTerm ? "Long-Term" : "Short-Term")})");
                        col.Item().Row(row =>
                        {
                            row.RelativeItem().Text($"    Cost Basis: {evt.CostBasis:C}  " +
                                                    $"Sale Price: {evt.SalePrice:C}");
                            row.ConstantItem(90)
                               .Text((evt.GainOrLoss >= 0 ? "Gain: " : "Loss: ") +
                                     Math.Abs(evt.GainOrLoss).ToString("C"))
                               .AlignRight()
                               .FontColor(evt.GainOrLoss >= 0 ? Colors.Green.Darken3 : Colors.Red.Darken3);
                        });
                    }
                }
            });
            page.Footer().AlignCenter().Text(x =>
            {
                x.Span("Generated by Herd Master — ");
                x.Span(DateTime.Now.ToString("MM/dd/yyyy HH:mm"));
            });
        })).GeneratePdf(path);
    }

    public void ExportCashFlowToPdf(CashFlowDto cf, DateTime from, DateTime to, string path)
    {
        Document.Create(c => c.Page(page =>
        {
            page.Size(PageSizes.A4);
            page.Margin(2, Unit.Centimetre);
            page.DefaultTextStyle(x => x.FontSize(10));
            page.Header().Text("Herd Master — Cash Flow Statement")
                .SemiBold().FontSize(16).FontColor(Colors.Green.Darken3);
            page.Content().Column(col =>
            {
                col.Spacing(5);
                col.Item().Text($"Period: {from:MMMM d, yyyy}  —  {to:MMMM d, yyyy}").Italic();
                col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                col.Item().PaddingTop(4).Text("OPERATING ACTIVITIES").Bold().FontSize(12);
                foreach (var item in cf.OperatingItems)
                    AddLineRow(col, item.Category, item.Amount, false);
                AddLineRow(col, "Net Cash from Operations", cf.OperatingActivities, true);

                col.Item().PaddingTop(6).Text("INVESTING ACTIVITIES").Bold().FontSize(12);
                foreach (var item in cf.InvestingItems)
                    AddLineRow(col, item.Category, item.Amount, false);
                AddLineRow(col, "Net Cash from Investing", cf.InvestingActivities, true);

                col.Item().PaddingTop(6).Text("FINANCING ACTIVITIES").Bold().FontSize(12);
                foreach (var item in cf.FinancingItems)
                    AddLineRow(col, item.Category, item.Amount, false);
                AddLineRow(col, "Net Cash from Financing", cf.FinancingActivities, true);

                col.Item().LineHorizontal(1).LineColor(Colors.Grey.Lighten2);
                col.Item().Row(row =>
                {
                    row.RelativeItem().Text("NET CASH CHANGE").Bold().FontSize(12);
                    row.ConstantItem(110).Text(cf.NetCashChange.ToString("C")).Bold().FontSize(12).AlignRight();
                });
            });
            page.Footer().AlignCenter().Text(x =>
            {
                x.Span("Generated by Herd Master — ");
                x.Span(DateTime.Now.ToString("MM/dd/yyyy HH:mm"));
            });
        })).GeneratePdf(path);
    }

    public void ExportBillOfSaleToPdf(TransactionDto sale, AnimalDto? animal, string farmName, string path)
    {
        Document.Create(c => c.Page(page =>
        {
            page.Size(PageSizes.A4);
            page.Margin(3, Unit.Centimetre);
            page.DefaultTextStyle(x => x.FontSize(11));
            page.Header().Column(col =>
            {
                col.Item().Text("BILL OF SALE")
                    .Bold().FontSize(22).FontColor(Colors.Green.Darken3).AlignCenter();
                col.Item().Text(farmName).FontSize(13).AlignCenter();
            });
            page.Content().Column(col =>
            {
                col.Spacing(10);
                col.Item().PaddingTop(10).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                col.Item().Row(row =>
                {
                    row.RelativeItem().Column(c =>
                    {
                        c.Item().Text("SELLER").Bold();
                        c.Item().Text(farmName);
                    });
                    row.RelativeItem().Column(c =>
                    {
                        c.Item().Text("DATE OF SALE").Bold();
                        c.Item().Text(sale.Date.ToString("MMMM d, yyyy"));
                    });
                });

                if (animal is not null)
                {
                    col.Item().LineHorizontal(0.5f).LineColor(Colors.Grey.Lighten2);
                    col.Item().Text("ANIMAL DESCRIPTION").Bold().FontSize(12);
                    col.Item().Row(row =>
                    {
                        row.RelativeItem().Column(c =>
                        {
                            c.Item().Text($"Name: {animal.BarnName}");
                            if (!string.IsNullOrEmpty(animal.RegisteredName))
                                c.Item().Text($"Registered: {animal.RegisteredName}");
                            c.Item().Text($"Breed: {animal.BreedName}");
                            c.Item().Text($"Gender: {animal.Gender}");
                        });
                        row.RelativeItem().Column(c =>
                        {
                            c.Item().Text($"Birth Date: {animal.BirthDate:MM/dd/yyyy}");
                            if (!string.IsNullOrEmpty(animal.TagNumber))
                                c.Item().Text($"Tag No.: {animal.TagNumber}");
                        });
                    });
                }

                col.Item().LineHorizontal(0.5f).LineColor(Colors.Grey.Lighten2);
                col.Item().Text("TRANSACTION DETAILS").Bold().FontSize(12);
                AddLineRow(col, sale.Description, sale.Amount, true, fontSize: 13);
                if (!string.IsNullOrEmpty(sale.PayeePayer))
                    col.Item().Text($"Buyer: {sale.PayeePayer}");
                if (!string.IsNullOrEmpty(sale.PaymentMethod))
                    col.Item().Text($"Payment Method: {sale.PaymentMethod}");

                col.Item().PaddingTop(20).LineHorizontal(0.5f).LineColor(Colors.Grey.Lighten2);
                col.Item().Row(row =>
                {
                    row.RelativeItem().Column(c =>
                    {
                        c.Item().PaddingTop(30).LineHorizontal(0.5f).LineColor(Colors.Black);
                        c.Item().Text("Seller Signature / Date");
                    });
                    row.ConstantItem(20);
                    row.RelativeItem().Column(c =>
                    {
                        c.Item().PaddingTop(30).LineHorizontal(0.5f).LineColor(Colors.Black);
                        c.Item().Text("Buyer Signature / Date");
                    });
                });
            });
            page.Footer().AlignCenter().Text(x =>
            {
                x.Span("Generated by Herd Master — ");
                x.Span(DateTime.Now.ToString("MM/dd/yyyy HH:mm"));
            });
        })).GeneratePdf(path);
    }

    private static void AddLineRow(ColumnDescriptor col, string label, decimal amount,
        bool bold, bool italic = false, float fontSize = 10)
    {
        col.Item().Row(row =>
        {
            var labelText = row.RelativeItem().Text(label);
            var amountText = row.ConstantItem(110).Text(amount.ToString("C")).AlignRight();
            if (bold)   { labelText.Bold();   amountText.Bold(); }
            if (italic) { labelText.Italic(); amountText.Italic(); }
            if (fontSize != 10) { labelText.FontSize(fontSize); amountText.FontSize(fontSize); }
        });
    }

    private record CsvAnimalRow(AnimalDto A)
    {
        public string BarnName => A.BarnName;
        public string? RegisteredName => A.RegisteredName;
        public string Breed => A.BreedName;
        public string Gender => A.Gender.ToString();
        public string Status => A.Status.ToString();
        public string BirthDate => A.BirthDate.ToString("MM/dd/yyyy");
        public string Age => A.AgeDisplay;
        public string Weight => A.WeightDisplay;
        public string Height => A.HeightDisplay;
        public string? Coloring => A.Coloring;
        public string? Location => A.CurrentLocation;
        public string? LastWorming => A.LastWormingDate?.ToString("MM/dd/yyyy");
        public string? LastVaccination => A.LastVaccinationDate?.ToString("MM/dd/yyyy");
        public string? Sire => A.SireBarnName ?? A.ExternalSireName;
        public string? Dam => A.DamBarnName ?? A.ExternalDamName;
    }
}
